sudo: required
services:
  - docker

before_install: 
  - docker build -t bryangranadilla911/front-end -f Dockerfile.dev .

script:
  - docker run bryangranadilla911/front-end npm run test -- --coverage