sudo: required
services:
  - docker

before_install: 
  - docker build -t bryangranadilla911/front-end -f Dockerfile.dev .

script:
  - docker run bryangranadilla911/front-end npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-348460717877"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"